## Data acqisition using Python for data science
#### by Chukiat Worasucheep
This notebook file has 3 parts:
1. Read/write CSV (comma separated value) files
2. Read tables from a HTML web page
3. BeautifulSoup library

## 1. Read/write CSV (comma separated value) files

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df = pd.read_csv('titanic.csv', usecols=[0, 1, 2, 4, 5])
df

     PassengerId  Survived  Pclass     Sex   Age
0              1         0       3    male  22.0
1              2         1       1  female  38.0
2              3         1       3  female  26.0
3              4         1       1  female  35.0
4              5         0       3    male  35.0
..           ...       ...     ...     ...   ...
886          887         0       2    male  27.0
887          888         1       1  female  19.0
888          889         0       3  female   NaN
889          890         1       1    male  26.0
890          891         0       3    male  32.0

[891 rows x 5 columns]

In [4]:
df = pd.read_csv('titanic.csv', 
                 usecols=[0, 1, 2, 4, 5], 
                 header=2, nrows=4)
df

   2  1  1.1  female    38
0  3  1    3  female  26.0
1  4  1    1  female  35.0
2  5  0    3    male  35.0
3  6  0    3    male   NaN

In [5]:
df = pd.read_csv('titanic.csv', index_col=0)
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.tail(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [9]:
df.to_csv('new.csv')

In [10]:
df.to_csv('new.csv', columns=['Survived', 'Age', 'Sex'])

In [11]:
df.to_csv('new.csv', sep=';', 
          columns=['Survived', 'Age', 'Sex'])

## 2. Read tables from a HTML web page

In [12]:
URL = 'https://en.wikipedia.org/wiki/Wonders_of_the_World'
dfs = pd.read_html(URL)
type(dfs), len(dfs)

(list, 4)

In [13]:
for i in range(len(dfs)):
      print('\n***************', i, '***************')
      print(dfs[i].head(10))

*************** 0 ***************
                      Wonder      Date started    Date finished  \
0             Channel Tunnel  December 1, 1987      May 6, 1994
1                   CN Tower  February 6, 1973    June 26, 1976
2      Empire State Building    March 17, 1930   April 11, 1931
3         Golden Gate Bridge   January 5, 1933     May 27, 1937
4                 Itaipú Dam      January 1970      May 5, 1984
5  Delta and Zuiderzee Works              1920     May 10, 1997
6               Panama Canal   January 1, 1880  January 7, 1914

                                            Location  \
0  Strait of Dover, in the English Channel betwee...
1                           Toronto, Ontario, Canada
2             New York City, New York, United States
3  Golden Gate Strait, north of San Francisco, Ca...
4  Paraná River, on the border between Brazil and...
5  Zeeland, South Holland, North Holland, Friesla...
6                                  Isthmus of Panama

                                        Significance
0  Longest undersea portion of any tunnel in the ...
1  Tallest freestanding structure in the world fr...
2  Tallest structure in the world from 1931 to 19...
3  Longest main span of any suspension bridge in ...
4  Largest operating hydroelectric facility in th...
5  Largest hydraulic engineering project undertak...
6  Allows passage of oceangoing vessels between t...

*************** 1 ***************
                                        Wonder  \
0                                Potala Palace
1                        Old City of Jerusalem
2                               Polar ice caps
3   Papahānaumokuākea Marine National Monument
4                                     Internet
5                                  Mayan ruins
6  Great Migration of Serengeti and Masai Mara
7   Grand Canyon (viewer-chosen eighth wonder)

                                       Location
0                                  Lhasa, Tibet
1                                  Israel [n 1]
2  Earth's polar regions (Arctic and Antarctic)
3                         Hawaii, United States
4                                           NaN
5                     Yucatán Peninsula, México
6                            Tanzania and Kenya
7                        Arizona, United States

*************** 2 ***************
                                Wonder                   Date of construction  \
0                  Great Wall of China               Since 7th century BC[21]
1                                Petra                              c. 100 BC
2                  Christ the Redeemer  opened to the public October 12, 1931
3                         Machu Picchu                             c. AD 1450
4                         Chichén Itzá                              c. AD 600
5                            Colosseum                        completed AD 80
6                            Taj Mahal                   completed c. AD 1648
7  Giza Pyramids (honorary candidates)                   completed c. 2560 BC

      Present-day location
0                    China
1            Ma'an, Jordan
2   Rio de Janeiro, Brazil
3  Urubamba Province, Peru
4          Yucatán, Mexico
5              Rome, Italy
6              Agra, India
7              Giza, Egypt

*************** 3 ***************
  .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteSeven Wonders of the Ancient World  \
0                                  The Seven Wonders
1                                            Related

  .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteSeven Wonders of the Ancient World.1
0  Great Pyramid of Giza Hanging Gardens of Babyl...
1  Wonders of the World Seven Wonders of the Worl...

In [14]:
dfs[1]

,Wonder,Location
0,Potala Palace,"Lhasa, Tibet"
1,Old City of Jerusalem,Israel [n 1]
2,Polar ice caps,Earth's polar regions (Arctic and Antarctic)
3,Papahānaumokuākea Marine National Monument,"Hawaii, United States"
4,Internet,NaN
5,Mayan ruins,"Yucatán Peninsula, México"
6,Great Migration of Serengeti and Masai Mara,Tanzania and Kenya
7,Grand Canyon (viewer-chosen eighth wonder),"Arizona, United States"

## 3. BeautifulSoup library

In [15]:
from bs4 import BeautifulSoup
import requests

In [18]:
webpage = requests.get('https://www.ttbbank.com/property/property/for-sale?type=&price=&province=10&amphur=&area=')
s = BeautifulSoup(webpage.text, 'html')
s

<!DOCTYPE html>
<!--[if lt IE 9]> <html lang="th" class="lt-ie9"> <![endif]--><!--[if IE 9]> <html lang="th" class="ie9"> <![endif]--><html lang="th">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
<title>ทรัพย์สินพร้อมขาย - ttb property</title>
<meta content="ค้นหาทรัพย์สินพร้อมขาย ทั้งบ้าน ทาวน์เฮ้าส์ คอนโดมิเนียม ที่ดิน และอสังหาฯ ประเภทอื่นๆ ของธนาคารทหารไทยธนชาต ที่พร้อมโอนกรรมสิทธิ์ให้คุณเป็นเจ้าของทันที" name="description"/>
<meta content="ttb property, ทรัพย์สินธนาคารทหารไทยธนชาต, ทรัพย์สินธนาคาร, ทรัพย์สินพร้อมขาย, ทรัพย์สินรอขาย, ค้นหาบ้าน, บ้านมือสอง, ที่ดิน, อาคารพาณิชย์, ทาวน์เฮ้าส์มือสอง, บ้านเดี่ยวมือสอง, คอนโดมือสอง, อสังหาริมทรัพย์" name="keywords"/>
<meta content="" property="og:locale"/>
<meta content="article" property="og:type"/>
<meta content="ทรัพย์สินพร้อมขาย - ttb property" property="og:title"/>
<meta content="https://www.ttbbank.com/property/property/for-sale" property="og:url"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon.ico" rel="shortcut icon"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/manifest.json" rel="manifest"/>
<meta content="#337ab7" name="msapplication-TileColor"/>
<meta content="https://www.ttbbank.com/property/assets/img/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#337ab7" name="theme-color"/>
<!-- OWL Theme -->
<link href="https://www.ttbbank.com/property/assets/js/owlcarousel/owl.carousel.min.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/js/owlcarousel/owl.theme.default.min.css" rel="stylesheet"/>
<!-- Ellipsis -->
<link href="https://www.ttbbank.com/property/assets/js/ellipsis/ellipsis-lastline.css" rel="stylesheet"/>
<!-- Chosen -->
<link href="https://www.ttbbank.com/property/assets/js/chosen/chosen.min.css" rel="stylesheet"/>
<!-- Themes TMB Property -->
<link href="https://www.ttbbank.com/property/assets/css/theme.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/css/theme-rwd.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/home/css/home.css" rel="stylesheet"/>
<!--[if lte IE 9]>
<link rel="stylesheet" href="https://www.ttbbank.com/property/assets/css/lte-ie9.css">
<![endif]-->
<!--[if lt IE 9]>
<script src="https://www.ttbbank.com/property/assets/js/utility/html5shiv.min.js"></script>
<script src="https://www.ttbbank.com/property/assets/js/utility/respond.min.js"></script>
<script src="https://www.ttbbank.com/property/assets/js/utility/selectivizr-min.js"></script>
<![endif]-->
<script>!function(e){var n="https://s.go-mpulse.net/boomerang/";if("False"=="True")e.BOOMR_config=e.BOOMR_config||{},e.BOOMR_config.PageParams=e.BOOMR_config.PageParams||{},e.BOOMR_config.PageParams.pci=!0,n="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="WKWQA-RHAFX-S22CE-HQPPS-V8ASK",function(){function e(){if(!o){var e=document.createElement("script");e.id="boomr-scr-as",e.src=window.BOOMR.url,e.async=!0,i.parentNode.appendChild(e),o=!0}}function t(e){o=!0;var n,t,a,r,d=document,O=window;if(window.BOOMR.snippetMethod=e?"if":"i",t=function(e,n){var t=d.createElement("script");t.id=n||"boomr-if-as",t.src=window.BOOMR.url,BOOMR_lstart=(new Date).getTime(),e=e||d.body,e.appendChild(t)},!window.addEventListener&&window.attachEvent&&navigator.userAgent.match(/MSIE [67]\./))return window.BOOMR.snippetMethod="s",void t(i.parentNode,"boomr-async");a=document.createElement("IFRAME"),a.src="about:blank",a.title="",a.role="presentation",a.loading="eager",r=(a.frameElement||a).style,r.width=0,r.height=0,r.border=0,r.display="none",i.parentNode.appendChild(a);try{O=a.contentWindow,d=O.document.open()}catch(_){n=document.domain,a.src="javascript:var d=document.open();d.domain='"+n+"';void(0);",O=a.contentWindow,d=O.document.open()}if(n)d._boomrl=function(){this.domain=n,t()},d.write("<bo"+"dy onload='document._boomrl();'>");else if(O._boomrl=function(){t()},O.addEventListener)O.addEventListener("load",O._boomrl,!1);else if(O.attachEvent)O.attachEvent("onload",O._boomrl);d.close()}function a(e){window.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!window.BOOMR||!window.BOOMR.version&&!window.BOOMR.snippetExecuted){window.BOOMR=window.BOOMR||{},window.BOOMR.snippetStart=(new Date).getTime(),window.BOOMR.snippetExecuted=!0,window.BOOMR.snippetVersion=12,window.BOOMR.url=n+"WKWQA-RHAFX-S22CE-HQPPS-V8ASK";var i=document.currentScript||document.getElementsByTagName("script")[0],o=!1,r=document.createElement("link");if(r.relList&&"function"==typeof r.relList.supports&&r.relList.supports("preload")&&"as"in r)window.BOOMR.snippetMethod="p",r.href=window.BOOMR.url,r.rel="preload",r.as="script",r.addEventListener("load",e),r.addEventListener("error",function(){t(!0)}),setTimeout(function(){if(!o)t(!0)},3e3),BOOMR_lstart=(new Date).getTime(),i.parentNode.appendChild(r);else t(!1);if(window.addEventListener)window.addEventListener("load",a,!1);else if(window.attachEvent)window.attachEvent("onload",a)}}(),"".length>0)if(e&&"performance"in e&&e.performance&&"function"==typeof e.performance.setResourceTimingBufferSize)e.performance.setResourceTimingBufferSize();!function(){if(BOOMR=e.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var n=""=="true"?1:0,t="",a="vnswsr5lmyfrayydg75a-f-5f2e87523-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,o={"ak.v":"32","ak.cp":"1265178","ak.ai":parseInt("760181",10),"ak.ol":"0","ak.cr":18,"ak.ipv":4,"ak.proto":"http/1.1","ak.rid":"2577119d","ak.r":32632,"ak.a2":n,"ak.m":"b","ak.n":"essl","ak.bpcip":"171.101.105.0","ak.cport":60217,"ak.gh":"171.102.11.12","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"reno","ak.t":"1661155322","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==AsieQP+EvYF2f7rdhApctlZVpy5TNJeD7c5eirbmUXBW7qWDMTxB2pp+WkvHX7J4I4dFjpNU3uym24IjeQzJ6vyO0YJfkhsmdso8mX2EirU1vOutckW4QkaNfxjk099z7DFYfyXbmYkCv6hgpYQo7PR2qCP8qI3cPqHvg4vPhsM118SiC+nO8JMH+HLRzd+vxQnmAec4/isjNvlNPEdJoLi5p9MKvbvaSNvx/7o9FdY4FTJRedydT/gTw8e54XdwA1MnB3WNvJxbCwSoD67DO9nq3ptdPrzJy7jS8WfwXhodEKB1epSPH068iQHOhqlB9lsWbjPTneqpjMKAYcagePkkDwvhHTQPo8OgowJT/9SO+FpRwpvY5YZ7LyO63YBei2oYUtT9KJlhvoHpREzBQn0WzdpXSEWrDz7qxacrT3E=","ak.pv":"24","ak.dpoabenc":"","ak.tf":i};if(""!==t)o["ak.ruds"]=t;var r={i:!1,av:function(n){var t="http.initiator";if(n&&(!n[t]||"spa_hard"===n[t]))o["ak.feo"]=void 0!==e.aFeoApplied?1:0,BOOMR.addVar(o)},rv:function(){var e=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(e)}};BOOMR.plugins.AK={akVars:o,akDNSPreFetchDomain:a,init:function(){if(!r.i){var e=BOOMR.subscribe;e("before_beacon",r.av,null,null),e("onbeacon",r.rv,null,null),r.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>
<body>
<script type="application/javascript">
var base_url	=	'https://www.ttbbank.com/property/';
var site_url	=	'https://www.ttbbank.com/property/';
</script>
<header class="header" id="header">
<div class="container">
<div class="logo-container">
<a href="https://www.ttbbank.com/property/">
<img alt="ttb Corporate Logo" class="logo-main" src="https://www.ttbbank.com/property/assets/img/logo-tmb.png"/>
<!--<img src="https://www.ttbbank.com/property/assets/img/logo.png" alt="TTB Corporate Logo" class="logo-main">-->
<img alt="Property" class="logo-property" src="https://www.ttbbank.com/property/assets/img/logo-property.png"/>
</a>
</div>
<div class="mnu-btn" id="toggle">
<span class="top"></span>
<span class="middle"></span>
<span class="bottom"></span>
</div>
<div class="overlay">
<nav class="overlay-menu">
<ul>
<li class="menu-item active"><a href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a></li>
<li class="menu-item"><a href="https://www.ttbbank.com/property/property/auction">ทรัพย์สินขายทอดตลาด</a></li>
<li class="menu-item"><a href="https://www.ttbbank.com/property/property/consignment">ทรัพย์สินฝากขาย</a></li>
</ul>
<div class="nav-bottom">
<div class="list-social">
<a href="https://www.facebook.com/ttbbankofficial" target="_blank"><i class="ic ic-facebook"></i></a>
<a href="https://twitter.com/ttbbankofficial" target="_blank"><i class="ic ic-twitter"></i></a>
</div>
<div class="copyright">© สงวนลิขสิทธิ์ 2560 ธนาคารทหารไทยธนชาต จํากัด (มหาชน)</div>
</div>
</nav>
</div>
<div class="search-container">
<a href="https://www.ttbbank.com/property/search"><i class="ic ic-search"></i></a>
</div>
</div>
</header>
<main class="main">
<section class="section-list">
<div class="container">
<div class="postcontent">
<div class="section-group">
<div class="section-subheading">
<h1 class="heading-h2">ทรัพย์สินพร้อมขาย </h1>
</div>
<form action="https://www.ttbbank.com/property/property/for-sale" class="searchform-inpage" id="formsearch" method="get">
<div class="input-group">
<input class="text-input" id="keyword" name="keyword" placeholder="รหัสทรัพย์สิน..." type="text" value=""/>
<button onclick="if($('#keyword').val()==''){$('#keyword').focus(); return false;}else{$('#formsearch').submit();}" type="submit"><span class="icon-search"></span>ค้นหา</button>
<div class="xfilter button-filter" id="filter">ตัวกรอง</div>
</div>
</form>
<div class="filter-container">
<div class="col-left">
<div class="dropdown-list">
<form class="form" id="sort_form" method="get">
<input name="province" type="hidden" value="10"/>
<div class="center">
<select class="custom-select sources" id="sort_price" name="sort" placeholder="เรียงตาม">
<option value="">ทรัพย์สินเด่น</option>
<option value="asc">ราคา (ต่ำ - สูง)</option>
<option value="desc">ราคา (สูง - ต่ำ)</option>
</select>
</div>
</form>
</div>
</div>
<div class="col-right">
<div class="search-result">ค้นพบ <span>216</span> รายการ</div>
</div>
</div>
<div class="clearall"></div>
<div class="landind-items">
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00186">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3746_20220512114823.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00186"><h3 data-ellipsis-lastline="">ห้องชุด  PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 950/52 ชั้น 6 โครงการบ้านอุดมสุขคอนโดมิเนี่ยม 2 ซอยอุดมสุข 42 (บางนาตราด 19 แยก 14) ถนนอุดมสุข แขวงบางนา เขตพระโขนง กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 23.37 ตร.ม.</p>
</div>
<p class="entry-price">234,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00186</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/C10125">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3013_20210621171407.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/C10125"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 1638/90 โครงการ 101 แมนชั่นคอนโดมิเนียม ถนนลาดพร้าว ซอย 101 แยก 38 (สันติสุข) แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 33.56 ตร.ม.</p>
</div>
<p class="entry-price">425,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">C10125</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12100">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3919_20220803201316.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12100"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">477/18 ชั้น 2 อาคาร ซี อาคารชุดเทพลีลา คอนโดทาวน์ ซอยพระยาประเสริฐ แขวงวังทองหลาง เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 24.3 ตร.ม.</p>
</div>
<p class="entry-price">454,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12100</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00001">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3789_20220511143250.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00001"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">312/213 ชั้น 7 อาคาร A อาคารชุดบ้านพระยาภิรมย์-รัชดา ซอยรัชดาภิเษก 36 (เสือใหญ่อุทิศ) แยก 11  แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 31.86 ตร.ม.</p>
</div>
<p class="entry-price">513,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00001</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00212">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/2602_20210216142619.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00212"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">3272/110 ชั้น 5 อาคาร อี2 อาคารชุดซิตี้ วิลล่า ซอยลาดพร้าว126 ถนนลาดพร้าว แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 32.88 ตร.ม.</p>
</div>
<p class="entry-price">902,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00212</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12648">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/2489_20201103165949.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12648"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">16/129 ชั้น 5 อาคาร E อาคารชุดสมาร์ทคอนโด พระราม 2 ถนนบางขุนเทียน 16 แขวงแสมดำ เขตบางขุนเทียน กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 28.5 ตร.ม.</p>
</div>
<p class="entry-price">1,004,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12648</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
</div> <div class="pagination-container">
<ul class="pagination"><li class="disabled"><span class="disabled"><i class="ic ic-arrow-left"></i></span></li><li class="active"><span class="current">1</span> </li><li class=""><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=2">2</a> </li><li class="disabled"><span>...</span></li><li><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=36">36</a></li><li class=""><a class="next" href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=2"><i class="ic ic-arrow-right"></i></a></li></ul> </div>
</div>
</div>
<div class="sidebar" id="filter-sidebar">
<div class="modal-sidebar">
<div class="sidebar-content sidebar-filter">
<form action="https://www.ttbbank.com/property/property/for-sale" class="fieldset-group" method="get">
<div class="modal-header">
<h3>ตัวกรอง</h3>
<a class="icon-close xfilter" href="#"><i class="ic ic-close"></i></a>
</div>
<div class="field">
<label class="label-form">ประเภท / ราคา</label>
<div class="row">
<div class="col-filter col-xs-6 col-sm-6 col-md-12">
<div class="styled-select">
<select class="chosen-select" name="type">
<option value="">ทุกประเภท</option>
<option value="1">บ้าน</option>
<option value="3">ห้องชุด</option>
<option value="2">ทาวน์เฮ้าส์</option>
<option value="4">อาคารพาณิชย์</option>
<option value="5">ที่ดินเปล่า</option>
<option value="149">อื่นๆ</option>

In [19]:
webpage = requests.get('https://www.ttbbank.com/property/property/for-sale?type=&price=&province=10&amphur=&area=')
#soup = BeautifulSoup(webpage.text, 'lxml')
soup = BeautifulSoup(webpage.text, 'html')
soup

<!DOCTYPE html>
<!--[if lt IE 9]> <html lang="th" class="lt-ie9"> <![endif]--><!--[if IE 9]> <html lang="th" class="ie9"> <![endif]--><html lang="th">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
<title>ทรัพย์สินพร้อมขาย - ttb property</title>
<meta content="ค้นหาทรัพย์สินพร้อมขาย ทั้งบ้าน ทาวน์เฮ้าส์ คอนโดมิเนียม ที่ดิน และอสังหาฯ ประเภทอื่นๆ ของธนาคารทหารไทยธนชาต ที่พร้อมโอนกรรมสิทธิ์ให้คุณเป็นเจ้าของทันที" name="description"/>
<meta content="ttb property, ทรัพย์สินธนาคารทหารไทยธนชาต, ทรัพย์สินธนาคาร, ทรัพย์สินพร้อมขาย, ทรัพย์สินรอขาย, ค้นหาบ้าน, บ้านมือสอง, ที่ดิน, อาคารพาณิชย์, ทาวน์เฮ้าส์มือสอง, บ้านเดี่ยวมือสอง, คอนโดมือสอง, อสังหาริมทรัพย์" name="keywords"/>
<meta content="" property="og:locale"/>
<meta content="article" property="og:type"/>
<meta content="ทรัพย์สินพร้อมขาย - ttb property" property="og:title"/>
<meta content="https://www.ttbbank.com/property/property/for-sale" property="og:url"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon.ico" rel="shortcut icon"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/manifest.json" rel="manifest"/>
<meta content="#337ab7" name="msapplication-TileColor"/>
<meta content="https://www.ttbbank.com/property/assets/img/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#337ab7" name="theme-color"/>
<!-- OWL Theme -->
<link href="https://www.ttbbank.com/property/assets/js/owlcarousel/owl.carousel.min.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/js/owlcarousel/owl.theme.default.min.css" rel="stylesheet"/>
<!-- Ellipsis -->
<link href="https://www.ttbbank.com/property/assets/js/ellipsis/ellipsis-lastline.css" rel="stylesheet"/>
<!-- Chosen -->
<link href="https://www.ttbbank.com/property/assets/js/chosen/chosen.min.css" rel="stylesheet"/>
<!-- Themes TMB Property -->
<link href="https://www.ttbbank.com/property/assets/css/theme.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/css/theme-rwd.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/home/css/home.css" rel="stylesheet"/>
<!--[if lte IE 9]>
<link rel="stylesheet" href="https://www.ttbbank.com/property/assets/css/lte-ie9.css">
<![endif]-->
<!--[if lt IE 9]>
<script src="https://www.ttbbank.com/property/assets/js/utility/html5shiv.min.js"></script>
<script src="https://www.ttbbank.com/property/assets/js/utility/respond.min.js"></script>
<script src="https://www.ttbbank.com/property/assets/js/utility/selectivizr-min.js"></script>
<![endif]-->
<script>!function(e){var n="https://s.go-mpulse.net/boomerang/";if("False"=="True")e.BOOMR_config=e.BOOMR_config||{},e.BOOMR_config.PageParams=e.BOOMR_config.PageParams||{},e.BOOMR_config.PageParams.pci=!0,n="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="WKWQA-RHAFX-S22CE-HQPPS-V8ASK",function(){function e(){if(!o){var e=document.createElement("script");e.id="boomr-scr-as",e.src=window.BOOMR.url,e.async=!0,i.parentNode.appendChild(e),o=!0}}function t(e){o=!0;var n,t,a,r,d=document,O=window;if(window.BOOMR.snippetMethod=e?"if":"i",t=function(e,n){var t=d.createElement("script");t.id=n||"boomr-if-as",t.src=window.BOOMR.url,BOOMR_lstart=(new Date).getTime(),e=e||d.body,e.appendChild(t)},!window.addEventListener&&window.attachEvent&&navigator.userAgent.match(/MSIE [67]\./))return window.BOOMR.snippetMethod="s",void t(i.parentNode,"boomr-async");a=document.createElement("IFRAME"),a.src="about:blank",a.title="",a.role="presentation",a.loading="eager",r=(a.frameElement||a).style,r.width=0,r.height=0,r.border=0,r.display="none",i.parentNode.appendChild(a);try{O=a.contentWindow,d=O.document.open()}catch(_){n=document.domain,a.src="javascript:var d=document.open();d.domain='"+n+"';void(0);",O=a.contentWindow,d=O.document.open()}if(n)d._boomrl=function(){this.domain=n,t()},d.write("<bo"+"dy onload='document._boomrl();'>");else if(O._boomrl=function(){t()},O.addEventListener)O.addEventListener("load",O._boomrl,!1);else if(O.attachEvent)O.attachEvent("onload",O._boomrl);d.close()}function a(e){window.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!window.BOOMR||!window.BOOMR.version&&!window.BOOMR.snippetExecuted){window.BOOMR=window.BOOMR||{},window.BOOMR.snippetStart=(new Date).getTime(),window.BOOMR.snippetExecuted=!0,window.BOOMR.snippetVersion=12,window.BOOMR.url=n+"WKWQA-RHAFX-S22CE-HQPPS-V8ASK";var i=document.currentScript||document.getElementsByTagName("script")[0],o=!1,r=document.createElement("link");if(r.relList&&"function"==typeof r.relList.supports&&r.relList.supports("preload")&&"as"in r)window.BOOMR.snippetMethod="p",r.href=window.BOOMR.url,r.rel="preload",r.as="script",r.addEventListener("load",e),r.addEventListener("error",function(){t(!0)}),setTimeout(function(){if(!o)t(!0)},3e3),BOOMR_lstart=(new Date).getTime(),i.parentNode.appendChild(r);else t(!1);if(window.addEventListener)window.addEventListener("load",a,!1);else if(window.attachEvent)window.attachEvent("onload",a)}}(),"".length>0)if(e&&"performance"in e&&e.performance&&"function"==typeof e.performance.setResourceTimingBufferSize)e.performance.setResourceTimingBufferSize();!function(){if(BOOMR=e.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var n=""=="true"?1:0,t="",a="vnswsr5lmyfrayydg76a-f-46db3d850-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,o={"ak.v":"32","ak.cp":"1265178","ak.ai":parseInt("760181",10),"ak.ol":"0","ak.cr":18,"ak.ipv":4,"ak.proto":"http/1.1","ak.rid":"25773e4d","ak.r":32632,"ak.a2":n,"ak.m":"b","ak.n":"essl","ak.bpcip":"171.101.105.0","ak.cport":60218,"ak.gh":"171.102.11.12","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"reno","ak.t":"1661155324","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==rRo8QWVjBGpKE1kyb5cKTJoq+l23K8ixMTUSxZ8INvNCY6YS+UdGblYxe4suIrYNZBooouWSBHY+iBjabymA/7+0mssU4LRcg2HVsYd5xw6fZkrOUPM88HIoX/LkahAFxBhd2Zs1bQm6jlDeFeTVY9QTCYm3iC/Kt7N4+ASqsxk8gyMx/iLQ2Q/hS+6R0UQlhSWlWF4+1eLYMyeQHkEyGraAjBWMVDnMDhfuW5Szrznoxg6GbOn1KtTo4oMacnCtiUJcXiCzcZlpIwyJn8hwZ2/It0bTwKWCfNfnXPk9x7kAnoOOrjKhlv5FNdrotZ1Pf7k6x75oOMb9fEPiQ8C+b3yvEk9+DJGqgT/CNp+glBLcGG3lXTHCiQZSN9T2VH82XR2othHiehxsUgtpjeMkVFMoQB229UVqG/4Fl1JE5FU=","ak.pv":"24","ak.dpoabenc":"","ak.tf":i};if(""!==t)o["ak.ruds"]=t;var r={i:!1,av:function(n){var t="http.initiator";if(n&&(!n[t]||"spa_hard"===n[t]))o["ak.feo"]=void 0!==e.aFeoApplied?1:0,BOOMR.addVar(o)},rv:function(){var e=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(e)}};BOOMR.plugins.AK={akVars:o,akDNSPreFetchDomain:a,init:function(){if(!r.i){var e=BOOMR.subscribe;e("before_beacon",r.av,null,null),e("onbeacon",r.rv,null,null),r.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>
<body>
<script type="application/javascript">
var base_url	=	'https://www.ttbbank.com/property/';
var site_url	=	'https://www.ttbbank.com/property/';
</script>
<header class="header" id="header">
<div class="container">
<div class="logo-container">
<a href="https://www.ttbbank.com/property/">
<img alt="ttb Corporate Logo" class="logo-main" src="https://www.ttbbank.com/property/assets/img/logo-tmb.png"/>
<!--<img src="https://www.ttbbank.com/property/assets/img/logo.png" alt="TTB Corporate Logo" class="logo-main">-->
<img alt="Property" class="logo-property" src="https://www.ttbbank.com/property/assets/img/logo-property.png"/>
</a>
</div>
<div class="mnu-btn" id="toggle">
<span class="top"></span>
<span class="middle"></span>
<span class="bottom"></span>
</div>
<div class="overlay">
<nav class="overlay-menu">
<ul>
<li class="menu-item active"><a href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a></li>
<li class="menu-item"><a href="https://www.ttbbank.com/property/property/auction">ทรัพย์สินขายทอดตลาด</a></li>
<li class="menu-item"><a href="https://www.ttbbank.com/property/property/consignment">ทรัพย์สินฝากขาย</a></li>
</ul>
<div class="nav-bottom">
<div class="list-social">
<a href="https://www.facebook.com/ttbbankofficial" target="_blank"><i class="ic ic-facebook"></i></a>
<a href="https://twitter.com/ttbbankofficial" target="_blank"><i class="ic ic-twitter"></i></a>
</div>
<div class="copyright">© สงวนลิขสิทธิ์ 2560 ธนาคารทหารไทยธนชาต จํากัด (มหาชน)</div>
</div>
</nav>
</div>
<div class="search-container">
<a href="https://www.ttbbank.com/property/search"><i class="ic ic-search"></i></a>
</div>
</div>
</header>
<main class="main">
<section class="section-list">
<div class="container">
<div class="postcontent">
<div class="section-group">
<div class="section-subheading">
<h1 class="heading-h2">ทรัพย์สินพร้อมขาย </h1>
</div>
<form action="https://www.ttbbank.com/property/property/for-sale" class="searchform-inpage" id="formsearch" method="get">
<div class="input-group">
<input class="text-input" id="keyword" name="keyword" placeholder="รหัสทรัพย์สิน..." type="text" value=""/>
<button onclick="if($('#keyword').val()==''){$('#keyword').focus(); return false;}else{$('#formsearch').submit();}" type="submit"><span class="icon-search"></span>ค้นหา</button>
<div class="xfilter button-filter" id="filter">ตัวกรอง</div>
</div>
</form>
<div class="filter-container">
<div class="col-left">
<div class="dropdown-list">
<form class="form" id="sort_form" method="get">
<input name="province" type="hidden" value="10"/>
<div class="center">
<select class="custom-select sources" id="sort_price" name="sort" placeholder="เรียงตาม">
<option value="">ทรัพย์สินเด่น</option>
<option value="asc">ราคา (ต่ำ - สูง)</option>
<option value="desc">ราคา (สูง - ต่ำ)</option>
</select>
</div>
</form>
</div>
</div>
<div class="col-right">
<div class="search-result">ค้นพบ <span>216</span> รายการ</div>
</div>
</div>
<div class="clearall"></div>
<div class="landind-items">
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00186">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3746_20220512114823.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00186"><h3 data-ellipsis-lastline="">ห้องชุด  PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 950/52 ชั้น 6 โครงการบ้านอุดมสุขคอนโดมิเนี่ยม 2 ซอยอุดมสุข 42 (บางนาตราด 19 แยก 14) ถนนอุดมสุข แขวงบางนา เขตพระโขนง กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 23.37 ตร.ม.</p>
</div>
<p class="entry-price">234,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00186</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/C10125">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3013_20210621171407.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/C10125"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 1638/90 โครงการ 101 แมนชั่นคอนโดมิเนียม ถนนลาดพร้าว ซอย 101 แยก 38 (สันติสุข) แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 33.56 ตร.ม.</p>
</div>
<p class="entry-price">425,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">C10125</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12100">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3919_20220803201316.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12100"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">477/18 ชั้น 2 อาคาร ซี อาคารชุดเทพลีลา คอนโดทาวน์ ซอยพระยาประเสริฐ แขวงวังทองหลาง เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 24.3 ตร.ม.</p>
</div>
<p class="entry-price">454,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12100</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00001">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3789_20220511143250.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00001"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">312/213 ชั้น 7 อาคาร A อาคารชุดบ้านพระยาภิรมย์-รัชดา ซอยรัชดาภิเษก 36 (เสือใหญ่อุทิศ) แยก 11  แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 31.86 ตร.ม.</p>
</div>
<p class="entry-price">513,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00001</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00212">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/2602_20210216142619.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00212"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">3272/110 ชั้น 5 อาคาร อี2 อาคารชุดซิตี้ วิลล่า ซอยลาดพร้าว126 ถนนลาดพร้าว แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 32.88 ตร.ม.</p>
</div>
<p class="entry-price">902,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00212</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12648">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/2489_20201103165949.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12648"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">16/129 ชั้น 5 อาคาร E อาคารชุดสมาร์ทคอนโด พระราม 2 ถนนบางขุนเทียน 16 แขวงแสมดำ เขตบางขุนเทียน กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 28.5 ตร.ม.</p>
</div>
<p class="entry-price">1,004,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12648</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
</div> <div class="pagination-container">
<ul class="pagination"><li class="disabled"><span class="disabled"><i class="ic ic-arrow-left"></i></span></li><li class="active"><span class="current">1</span> </li><li class=""><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=2">2</a> </li><li class="disabled"><span>...</span></li><li><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=36">36</a></li><li class=""><a class="next" href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=2"><i class="ic ic-arrow-right"></i></a></li></ul> </div>
</div>
</div>
<div class="sidebar" id="filter-sidebar">
<div class="modal-sidebar">
<div class="sidebar-content sidebar-filter">
<form action="https://www.ttbbank.com/property/property/for-sale" class="fieldset-group" method="get">
<div class="modal-header">
<h3>ตัวกรอง</h3>
<a class="icon-close xfilter" href="#"><i class="ic ic-close"></i></a>
</div>
<div class="field">
<label class="label-form">ประเภท / ราคา</label>
<div class="row">
<div class="col-filter col-xs-6 col-sm-6 col-md-12">
<div class="styled-select">
<select class="chosen-select" name="type">
<option value="">ทุกประเภท</option>
<option value="1">บ้าน</option>
<option value="3">ห้องชุด</option>
<option value="2">ทาวน์เฮ้าส์</option>
<option value="4">อาคารพาณิชย์</option>
<option value="5">ที่ดินเปล่า</option>
<option value="149">อื่นๆ</option>

In [20]:
prop_list = soup.find('div', class_ = 'landind-items')
type(prop_list)

bs4.element.Tag

In [21]:
prop_list

<div class="landind-items">
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00186">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3746_20220512114823.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00186"><h3 data-ellipsis-lastline="">ห้องชุด  PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 950/52 ชั้น 6 โครงการบ้านอุดมสุขคอนโดมิเนี่ยม 2 ซอยอุดมสุข 42 (บางนาตราด 19 แยก 14) ถนนอุดมสุข แขวงบางนา เขตพระโขนง กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 23.37 ตร.ม.</p>
</div>
<p class="entry-price">234,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00186</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/C10125">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3013_20210621171407.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/C10125"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 1638/90 โครงการ 101 แมนชั่นคอนโดมิเนียม ถนนลาดพร้าว ซอย 101 แยก 38 (สันติสุข) แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 33.56 ตร.ม.</p>
</div>
<p class="entry-price">425,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">C10125</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12100">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3919_20220803201316.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12100"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">477/18 ชั้น 2 อาคาร ซี อาคารชุดเทพลีลา คอนโดทาวน์ ซอยพระยาประเสริฐ แขวงวังทองหลาง เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 24.3 ตร.ม.</p>
</div>
<p class="entry-price">454,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12100</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00001">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3789_20220511143250.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00001"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">312/213 ชั้น 7 อาคาร A อาคารชุดบ้านพระยาภิรมย์-รัชดา ซอยรัชดาภิเษก 36 (เสือใหญ่อุทิศ) แยก 11  แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 31.86 ตร.ม.</p>
</div>
<p class="entry-price">513,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00001</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00212">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/2602_20210216142619.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00212"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">3272/110 ชั้น 5 อาคาร อี2 อาคารชุดซิตี้ วิลล่า ซอยลาดพร้าว126 ถนนลาดพร้าว แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 32.88 ตร.ม.</p>
</div>
<p class="entry-price">902,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00212</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12648">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/2489_20201103165949.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12648"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">16/129 ชั้น 5 อาคาร E อาคารชุดสมาร์ทคอนโด พระราม 2 ถนนบางขุนเทียน 16 แขวงแสมดำ เขตบางขุนเทียน กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 28.5 ตร.ม.</p>
</div>
<p class="entry-price">1,004,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12648</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
</div>

In [22]:
code = prop_list.find('div', class_ = 'entry-code').text
code

'P00186'

In [23]:
desc = prop_list.find('p', class_ = 'entry-desc').text
desc

'ห้องชุดเลขที่ 950/52 ชั้น 6 โครงการบ้านอุดมสุขคอนโดมิเนี่ยม 2 ซอยอุดมสุข 42 (บางนาตราด 19 แยก 14) ถนนอุดมสุข แขวงบางนา เขตพระโขนง กรุงเทพมหานคร'

In [24]:
area = prop_list.find('p', class_ = 'entry-area').text
area

'0000-0-00.0 / 23.37 ตร.ม.'

In [25]:
price = prop_list.find('p', class_ = 'entry-price').text
price

'234,000บาท'

In [26]:
image = prop_list.find('img').attrs['src']
image

'https://media.tmbbank.com/uploads/npa/product/img/3746_20220512114823.jpg'

In [27]:
link = prop_list.find('a').attrs['href']
link

'https://www.ttbbank.com/property/property/detail/P00186'

In [28]:
properties = soup.find_all('div', class_ = 'col-list-items')

In [29]:
for prop in properties:
    code  = prop.find('div', class_ = 'entry-code').text
    desc  = prop.find('p', class_ = 'entry-desc').text
    area  = prop.find('p', class_ = 'entry-area').text
    price = prop.find('p', class_ = 'entry-price').text
    image = prop.find('img').attrs['src']
    link  = prop.find('a').attrs['href']
    print(f'Code : {code}')
    print(f'Desc : {desc}')
    print(f'Area : {area}')
    print(f'Price: {price}')
    print(f'Image: {image}')
    print(f'Link : {link}')
    print()

Code : P00186
Desc : ห้องชุดเลขที่ 950/52 ชั้น 6 โครงการบ้านอุดมสุขคอนโดมิเนี่ยม 2 ซอยอุดมสุข 42 (บางนาตราด 19 แยก 14) ถนนอุดมสุข แขวงบางนา เขตพระโขนง กรุงเทพมหานคร
Area : 0000-0-00.0 / 23.37 ตร.ม.
Price: 234,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3746_20220512114823.jpg
Link : https://www.ttbbank.com/property/property/detail/P00186

Code : C10125
Desc : ห้องชุดเลขที่ 1638/90 โครงการ 101 แมนชั่นคอนโดมิเนียม ถนนลาดพร้าว ซอย 101 แยก 38 (สันติสุข) แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร
Area : 0000-0-00.0 / 33.56 ตร.ม.
Price: 425,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3013_20210621171407.jpg
Link : https://www.ttbbank.com/property/property/detail/C10125

Code : B12100
Desc : 477/18 ชั้น 2 อาคาร ซี อาคารชุดเทพลีลา คอนโดทาวน์ ซอยพระยาประเสริฐ แขวงวังทองหลาง เขตบางกะปิ กรุงเทพมหานคร
Area : 0000-0-00.0 / 24.3 ตร.ม.
Price: 454,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3919_20220803201316.jpg
Link : https://www.ttbbank.com/property/property/detail/B12100

Code : P00001
Desc : 312/213 ชั้น 7 อาคาร A อาคารชุดบ้านพระยาภิรมย์-รัชดา ซอยรัชดาภิเษก 36 (เสือใหญ่อุทิศ) แยก 11  แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร
Area : 0000-0-00.0 / 31.86 ตร.ม.
Price: 513,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3789_20220511143250.jpg
Link : https://www.ttbbank.com/property/property/detail/P00001

Code : P00212
Desc : 3272/110 ชั้น 5 อาคาร อี2 อาคารชุดซิตี้ วิลล่า ซอยลาดพร้าว126 ถนนลาดพร้าว แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร
Area : 0000-0-00.0 / 32.88 ตร.ม.
Price: 902,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/2602_20210216142619.jpg
Link : https://www.ttbbank.com/property/property/detail/P00212

Code : B12648
Desc : 16/129 ชั้น 5 อาคาร E อาคารชุดสมาร์ทคอนโด พระราม 2 ถนนบางขุนเทียน 16 แขวงแสมดำ เขตบางขุนเทียน กรุงเทพมหานคร
Area : 0000-0-00.0 / 28.5 ตร.ม.
Price: 1,004,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/2489_20201103165949.jpg
Link : https://www.ttbbank.com/property/property/detail/B12648

### Find links to pagination (next/previous pages)

In [30]:
pagination = soup.find('ul', class_ = 'pagination')
pagination.prettify()

'<ul class="pagination">\n <li class="disabled">\n  <span class="disabled">\n   <i class="ic ic-arrow-left">\n   </i>\n  </span>\n </li>\n <li class="active">\n  <span class="current">\n   1\n  </span>\n </li>\n <li class="">\n  <a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=2">\n   2\n  </a>\n </li>\n <li class="disabled">\n  <span>\n   ...\n  </span>\n </li>\n <li>\n  <a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=36">\n   36\n  </a>\n </li>\n <li class="">\n  <a class="next" href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=2">\n   <i class="ic ic-arrow-right">\n   </i>\n  </a>\n </li>\n</ul>\n'

In [31]:
line = pagination.find('li', class_ = 'active')
line

In [32]:
hlink = pagination.find('a', class_ = 'next').attrs['href']
hlink

'https://www.ttbbank.com/property/property/for-sale?type=&price=&province=10&amphur=&area=&limit=6&page=2'

### Browse to the next page

In [33]:
nextpage = requests.get(hlink)
soup = BeautifulSoup(nextpage.text, 'html')
soup

<!DOCTYPE html>
<!--[if lt IE 9]> <html lang="th" class="lt-ie9"> <![endif]--><!--[if IE 9]> <html lang="th" class="ie9"> <![endif]--><html lang="th">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
<title>ทรัพย์สินพร้อมขาย - ttb property</title>
<meta content="ค้นหาทรัพย์สินพร้อมขาย ทั้งบ้าน ทาวน์เฮ้าส์ คอนโดมิเนียม ที่ดิน และอสังหาฯ ประเภทอื่นๆ ของธนาคารทหารไทยธนชาต ที่พร้อมโอนกรรมสิทธิ์ให้คุณเป็นเจ้าของทันที" name="description"/>
<meta content="ttb property, ทรัพย์สินธนาคารทหารไทยธนชาต, ทรัพย์สินธนาคาร, ทรัพย์สินพร้อมขาย, ทรัพย์สินรอขาย, ค้นหาบ้าน, บ้านมือสอง, ที่ดิน, อาคารพาณิชย์, ทาวน์เฮ้าส์มือสอง, บ้านเดี่ยวมือสอง, คอนโดมือสอง, อสังหาริมทรัพย์" name="keywords"/>
<meta content="" property="og:locale"/>
<meta content="article" property="og:type"/>
<meta content="ทรัพย์สินพร้อมขาย - ttb property" property="og:title"/>
<meta content="https://www.ttbbank.com/property/property/for-sale" property="og:url"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon.ico" rel="shortcut icon"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://www.ttbbank.com/property/assets/img/favicon/manifest.json" rel="manifest"/>
<meta content="#337ab7" name="msapplication-TileColor"/>
<meta content="https://www.ttbbank.com/property/assets/img/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#337ab7" name="theme-color"/>
<!-- OWL Theme -->
<link href="https://www.ttbbank.com/property/assets/js/owlcarousel/owl.carousel.min.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/js/owlcarousel/owl.theme.default.min.css" rel="stylesheet"/>
<!-- Ellipsis -->
<link href="https://www.ttbbank.com/property/assets/js/ellipsis/ellipsis-lastline.css" rel="stylesheet"/>
<!-- Chosen -->
<link href="https://www.ttbbank.com/property/assets/js/chosen/chosen.min.css" rel="stylesheet"/>
<!-- Themes TMB Property -->
<link href="https://www.ttbbank.com/property/assets/css/theme.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/css/theme-rwd.css" rel="stylesheet"/>
<link href="https://www.ttbbank.com/property/assets/home/css/home.css" rel="stylesheet"/>
<!--[if lte IE 9]>
<link rel="stylesheet" href="https://www.ttbbank.com/property/assets/css/lte-ie9.css">
<![endif]-->
<!--[if lt IE 9]>
<script src="https://www.ttbbank.com/property/assets/js/utility/html5shiv.min.js"></script>
<script src="https://www.ttbbank.com/property/assets/js/utility/respond.min.js"></script>
<script src="https://www.ttbbank.com/property/assets/js/utility/selectivizr-min.js"></script>
<![endif]-->
<script>!function(e){var n="https://s.go-mpulse.net/boomerang/";if("False"=="True")e.BOOMR_config=e.BOOMR_config||{},e.BOOMR_config.PageParams=e.BOOMR_config.PageParams||{},e.BOOMR_config.PageParams.pci=!0,n="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="WKWQA-RHAFX-S22CE-HQPPS-V8ASK",function(){function e(){if(!o){var e=document.createElement("script");e.id="boomr-scr-as",e.src=window.BOOMR.url,e.async=!0,i.parentNode.appendChild(e),o=!0}}function t(e){o=!0;var n,t,a,r,d=document,O=window;if(window.BOOMR.snippetMethod=e?"if":"i",t=function(e,n){var t=d.createElement("script");t.id=n||"boomr-if-as",t.src=window.BOOMR.url,BOOMR_lstart=(new Date).getTime(),e=e||d.body,e.appendChild(t)},!window.addEventListener&&window.attachEvent&&navigator.userAgent.match(/MSIE [67]\./))return window.BOOMR.snippetMethod="s",void t(i.parentNode,"boomr-async");a=document.createElement("IFRAME"),a.src="about:blank",a.title="",a.role="presentation",a.loading="eager",r=(a.frameElement||a).style,r.width=0,r.height=0,r.border=0,r.display="none",i.parentNode.appendChild(a);try{O=a.contentWindow,d=O.document.open()}catch(_){n=document.domain,a.src="javascript:var d=document.open();d.domain='"+n+"';void(0);",O=a.contentWindow,d=O.document.open()}if(n)d._boomrl=function(){this.domain=n,t()},d.write("<bo"+"dy onload='document._boomrl();'>");else if(O._boomrl=function(){t()},O.addEventListener)O.addEventListener("load",O._boomrl,!1);else if(O.attachEvent)O.attachEvent("onload",O._boomrl);d.close()}function a(e){window.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!window.BOOMR||!window.BOOMR.version&&!window.BOOMR.snippetExecuted){window.BOOMR=window.BOOMR||{},window.BOOMR.snippetStart=(new Date).getTime(),window.BOOMR.snippetExecuted=!0,window.BOOMR.snippetVersion=12,window.BOOMR.url=n+"WKWQA-RHAFX-S22CE-HQPPS-V8ASK";var i=document.currentScript||document.getElementsByTagName("script")[0],o=!1,r=document.createElement("link");if(r.relList&&"function"==typeof r.relList.supports&&r.relList.supports("preload")&&"as"in r)window.BOOMR.snippetMethod="p",r.href=window.BOOMR.url,r.rel="preload",r.as="script",r.addEventListener("load",e),r.addEventListener("error",function(){t(!0)}),setTimeout(function(){if(!o)t(!0)},3e3),BOOMR_lstart=(new Date).getTime(),i.parentNode.appendChild(r);else t(!1);if(window.addEventListener)window.addEventListener("load",a,!1);else if(window.attachEvent)window.attachEvent("onload",a)}}(),"".length>0)if(e&&"performance"in e&&e.performance&&"function"==typeof e.performance.setResourceTimingBufferSize)e.performance.setResourceTimingBufferSize();!function(){if(BOOMR=e.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var n=""=="true"?1:0,t="",a="vnswsr5lmyfrayydhala-f-003fc55bd-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,o={"ak.v":"32","ak.cp":"1265178","ak.ai":parseInt("760181",10),"ak.ol":"0","ak.cr":17,"ak.ipv":4,"ak.proto":"http/1.1","ak.rid":"257a17ff","ak.r":32632,"ak.a2":n,"ak.m":"b","ak.n":"essl","ak.bpcip":"171.101.105.0","ak.cport":60219,"ak.gh":"171.102.11.12","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"reno","ak.t":"1661155350","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==ehj/6V/hAaJNJ1uaY97qmQsNuVhO9iCgwc+2U26uuTMFs0fhPW1FKqGlGyAcYOgXiGsa7cWbzYns9bQa4y8mMeR8pwXXEjvowiJNINsdTm2KZusAXA0mEpQyRWlWm+vcBRbuptR1VTeRxC6fuk3YYh6vQZezyQDD1fxw2bJDIrCEf2+d0+fsa3wAA+CRmK08zwM4mVLRqFZFzclSO2D4SzpO7T0gybyV4m2woVT7vuY9a4EF6j7x7d5RyVktgKljmJSm8OxnNgtRZ4MODRSOlo88pZf//Z5Rt0y7XK+XpP3pY3M7PsJ42KN7Hgew4F8c8ICC2lmQDvIgX+vgwT4jQ81lUQRk+Ztg/eSIQ6Up0b/FqYh32LSu3Lw2yd0JfblV064K8Ov65Nnjty68jFmBZw8oEYhIDoO9wQnSs6nEWTE=","ak.pv":"24","ak.dpoabenc":"","ak.tf":i};if(""!==t)o["ak.ruds"]=t;var r={i:!1,av:function(n){var t="http.initiator";if(n&&(!n[t]||"spa_hard"===n[t]))o["ak.feo"]=void 0!==e.aFeoApplied?1:0,BOOMR.addVar(o)},rv:function(){var e=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(e)}};BOOMR.plugins.AK={akVars:o,akDNSPreFetchDomain:a,init:function(){if(!r.i){var e=BOOMR.subscribe;e("before_beacon",r.av,null,null),e("onbeacon",r.rv,null,null),r.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>
<body>
<script type="application/javascript">
var base_url	=	'https://www.ttbbank.com/property/';
var site_url	=	'https://www.ttbbank.com/property/';
</script>
<header class="header" id="header">
<div class="container">
<div class="logo-container">
<a href="https://www.ttbbank.com/property/">
<img alt="ttb Corporate Logo" class="logo-main" src="https://www.ttbbank.com/property/assets/img/logo-tmb.png"/>
<!--<img src="https://www.ttbbank.com/property/assets/img/logo.png" alt="TTB Corporate Logo" class="logo-main">-->
<img alt="Property" class="logo-property" src="https://www.ttbbank.com/property/assets/img/logo-property.png"/>
</a>
</div>
<div class="mnu-btn" id="toggle">
<span class="top"></span>
<span class="middle"></span>
<span class="bottom"></span>
</div>
<div class="overlay">
<nav class="overlay-menu">
<ul>
<li class="menu-item active"><a href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a></li>
<li class="menu-item"><a href="https://www.ttbbank.com/property/property/auction">ทรัพย์สินขายทอดตลาด</a></li>
<li class="menu-item"><a href="https://www.ttbbank.com/property/property/consignment">ทรัพย์สินฝากขาย</a></li>
</ul>
<div class="nav-bottom">
<div class="list-social">
<a href="https://www.facebook.com/ttbbankofficial" target="_blank"><i class="ic ic-facebook"></i></a>
<a href="https://twitter.com/ttbbankofficial" target="_blank"><i class="ic ic-twitter"></i></a>
</div>
<div class="copyright">© สงวนลิขสิทธิ์ 2560 ธนาคารทหารไทยธนชาต จํากัด (มหาชน)</div>
</div>
</nav>
</div>
<div class="search-container">
<a href="https://www.ttbbank.com/property/search"><i class="ic ic-search"></i></a>
</div>
</div>
</header>
<main class="main">
<section class="section-list">
<div class="container">
<div class="postcontent">
<div class="section-group">
<div class="section-subheading">
<h1 class="heading-h2">ทรัพย์สินพร้อมขาย </h1>
</div>
<form action="https://www.ttbbank.com/property/property/for-sale" class="searchform-inpage" id="formsearch" method="get">
<div class="input-group">
<input class="text-input" id="keyword" name="keyword" placeholder="รหัสทรัพย์สิน..." type="text" value=""/>
<button onclick="if($('#keyword').val()==''){$('#keyword').focus(); return false;}else{$('#formsearch').submit();}" type="submit"><span class="icon-search"></span>ค้นหา</button>
<div class="xfilter button-filter" id="filter">ตัวกรอง</div>
</div>
</form>
<div class="filter-container">
<div class="col-left">
<div class="dropdown-list">
<form class="form" id="sort_form" method="get">
<input name="province" type="hidden" value="10"/>
<div class="center">
<select class="custom-select sources" id="sort_price" name="sort" placeholder="เรียงตาม">
<option value="">ทรัพย์สินเด่น</option>
<option value="asc">ราคา (ต่ำ - สูง)</option>
<option value="desc">ราคา (สูง - ต่ำ)</option>
</select>
</div>
</form>
</div>
</div>
<div class="col-right">
<div class="search-result">ค้นพบ <span>216</span> รายการ</div>
</div>
</div>
<div class="clearall"></div>
<div class="landind-items">
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12776">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3825_20220605081231.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12776"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">99/83 ชั้นล่าง อาคารบี อาคารชุดลุมพินี คอนโดทาวน์ บางแค  ถนนบางแค แขวงบางแค เขตบางแค กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 26.31 ตร.ม.</p>
</div>
<p class="entry-price">1,188,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">B12776</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/C10114">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3067_20210617172431.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/C10114"><h3 data-ellipsis-lastline="">ห้องชุด ttb</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 104/78 ชั้น4 อาคาร 3 โครงการไอริส แอเวนิว ถนนลาดกระบัง แขวงลาดกระบัง เขตลาดกระบัง กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 28.01 ตร.ม.</p>
</div>
<p class="entry-price">1,263,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">C10114</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00323">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3690_20220406191527.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00323"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 1/30 อาคาร เอ ชั้น 2 โครงการลุมพินีวิลล์ อ่อนนุช-พัฒนาการ ซอยอ่อนนุช 55-1 ถนนอ่อนนุช แขวงประเวศ เขตประเวศ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 22.66 ตร.ม.</p>
</div>
<p class="entry-price">1,322,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00323</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/B12196">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/281_20200220095812.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/B12196"><h3 data-ellipsis-lastline="">ทาวน์เฮ้าส์ ttb</h3></a>
<div class="box-group">
<p class="entry-desc">45 ซอยเพชรเกษม 79 แยก 1 ถนนเพชรเกษม แขวงหนองค้างพลู เขตหนองแขม กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-20.0 / 20 ตร.ว.</p>
</div>
<p class="entry-price">1,400,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=2">ทาวน์เฮ้าส์</a>
</div>
<div class="col-inline entry-code">B12196</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00365">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3117_20210621172149.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00365"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่ 194/101 ชั้น 4 อาคาร D โครงการเมโทรพาร์ค สาทร 3-2 ถนนกัลปพฤกษ์ แขวงบางหว้า เขตภาษีเจริญ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 31.61 ตร.ม.</p>
</div>
<p class="entry-price">1,496,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00365</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
<div class="col-list-items">
<div class="thumb-items list-items">
<div class="entry-img">
<a href="https://www.ttbbank.com/property/property/detail/P00361">
<img alt="" src="https://media.tmbbank.com/uploads/npa/product/img/3113_20210617120555.jpg"/>
</a>
</div>
<div class="box-inr">
<div class="entry-caption">
<a href="https://www.ttbbank.com/property/property/detail/P00361"><h3 data-ellipsis-lastline="">ห้องชุด PAMCO</h3></a>
<div class="box-group">
<p class="entry-desc">ห้องชุดเลขที่  164/74 ชั้น 7 อาคาร E โครงการเมโทรพาร์ค สาทร 2-2 แขวงบางหว้า เขตภาษีเจริญ กรุงเทพมหานคร</p>
<p class="entry-area">0000-0-00.0 / 30.1 ตร.ม.</p>
</div>
<p class="entry-price">1,524,000<span>บาท</span></p>
</div>
<div class="box-bottom">
<div class="entry-2col">
<div class="col-inline">
<a class="entry-tags" href="https://www.ttbbank.com/property/property/for-sale?type=3">ห้องชุด</a>
</div>
<div class="col-inline entry-code">P00361</div>
</div>
<div class="entry-bottom">
<a class="entry-category" href="https://www.ttbbank.com/property/property/for-sale">ทรัพย์สินพร้อมขาย </a>
</div>
</div>
</div>
</div>
</div>
</div> <div class="pagination-container">
<ul class="pagination"><li class=""><a class="prev" href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=1"><i class="ic ic-arrow-left"></i></a></li><li class=""><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=">1</a> </li><li class="active"><span class="current">2</span> </li><li class=""><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=3">3</a> </li><li class="disabled"><span>...</span></li><li><a href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=36">36</a></li><li class=""><a class="next" href="https://www.ttbbank.com/property/property/for-sale?type=&amp;price=&amp;province=10&amp;amphur=&amp;area=&amp;limit=6&amp;page=3"><i class="ic ic-arrow-right"></i></a></li></ul> </div>
</div>
</div>
<div class="sidebar" id="filter-sidebar">
<div class="modal-sidebar">
<div class="sidebar-content sidebar-filter">
<form action="https://www.ttbbank.com/property/property/for-sale" class="fieldset-group" method="get">
<div class="modal-header">
<h3>ตัวกรอง</h3>
<a class="icon-close xfilter" href="#"><i class="ic ic-close"></i></a>
</div>
<div class="field">
<label class="label-form">ประเภท / ราคา</label>
<div class="row">
<div class="col-filter col-xs-6 col-sm-6 col-md-12">
<div class="styled-select">
<select class="chosen-select" name="type">
<option value="">ทุกประเภท</option>
<option value="1">บ้าน</option>
<option value="3">ห้องชุด</option>

### Then extract information as before

In [34]:
properties = soup.find_all('div', class_ = 'col-list-items')

In [35]:
for prop in properties:
    code  = prop.find('div', class_ = 'entry-code').text
    desc  = prop.find('p', class_ = 'entry-desc').text
    area  = prop.find('p', class_ = 'entry-area').text
    price = prop.find('p', class_ = 'entry-price').text
    image = prop.find('img').attrs['src']
    link  = prop.find('a').attrs['href']
    print(f'Code : {code}')
    print(f'Desc : {desc}')
    print(f'Area : {area}')
    print(f'Price: {price}')
    print(f'Image: {image}')
    print(f'Link : {link}')
    print()

Code : B12776
Desc : 99/83 ชั้นล่าง อาคารบี อาคารชุดลุมพินี คอนโดทาวน์ บางแค  ถนนบางแค แขวงบางแค เขตบางแค กรุงเทพมหานคร
Area : 0000-0-00.0 / 26.31 ตร.ม.
Price: 1,188,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3825_20220605081231.jpg
Link : https://www.ttbbank.com/property/property/detail/B12776

Code : C10114
Desc : ห้องชุดเลขที่ 104/78 ชั้น4 อาคาร 3 โครงการไอริส แอเวนิว ถนนลาดกระบัง แขวงลาดกระบัง เขตลาดกระบัง กรุงเทพมหานคร
Area : 0000-0-00.0 / 28.01 ตร.ม.
Price: 1,263,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3067_20210617172431.jpg
Link : https://www.ttbbank.com/property/property/detail/C10114

Code : P00323
Desc : ห้องชุดเลขที่ 1/30 อาคาร เอ ชั้น 2 โครงการลุมพินีวิลล์ อ่อนนุช-พัฒนาการ ซอยอ่อนนุช 55-1 ถนนอ่อนนุช แขวงประเวศ เขตประเวศ กรุงเทพมหานคร
Area : 0000-0-00.0 / 22.66 ตร.ม.
Price: 1,322,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3690_20220406191527.jpg
Link : https://www.ttbbank.com/property/property/detail/P00323

Code : B12196
Desc : 45 ซอยเพชรเกษม 79 แยก 1 ถนนเพชรเกษม แขวงหนองค้างพลู เขตหนองแขม กรุงเทพมหานคร
Area : 0000-0-20.0 / 20 ตร.ว.
Price: 1,400,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/281_20200220095812.jpg
Link : https://www.ttbbank.com/property/property/detail/B12196

Code : P00365
Desc : ห้องชุดเลขที่ 194/101 ชั้น 4 อาคาร D โครงการเมโทรพาร์ค สาทร 3-2 ถนนกัลปพฤกษ์ แขวงบางหว้า เขตภาษีเจริญ กรุงเทพมหานคร
Area : 0000-0-00.0 / 31.61 ตร.ม.
Price: 1,496,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3117_20210621172149.jpg
Link : https://www.ttbbank.com/property/property/detail/P00365

Code : P00361
Desc : ห้องชุดเลขที่  164/74 ชั้น 7 อาคาร E โครงการเมโทรพาร์ค สาทร 2-2 แขวงบางหว้า เขตภาษีเจริญ กรุงเทพมหานคร
Area : 0000-0-00.0 / 30.1 ตร.ม.
Price: 1,524,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3113_20210617120555.jpg
Link : https://www.ttbbank.com/property/property/detail/P00361

In [36]:
webpage = requests.get('https://www.ttbbank.com/property/property/for-sale?type=&price=&province=10&amphur=&area=')
s = BeautifulSoup(webpage.text, 'html')
s

webpage = requests.get('https://www.ttbbank.com/property/property/for-sale?type=&price=&province=10&amphur=&area=')
#soup = BeautifulSoup(webpage.text, 'lxml')
soup = BeautifulSoup(webpage.text, 'html')
soup

prop_list = soup.find('div', class_ = 'landind-items')
type(prop_list)

prop_list

code = prop_list.find('div', class_ = 'entry-code').text
code

desc = prop_list.find('p', class_ = 'entry-desc').text
desc

area = prop_list.find('p', class_ = 'entry-area').text
area

price = prop_list.find('p', class_ = 'entry-price').text
price

image = prop_list.find('img').attrs['src']
image

link = prop_list.find('a').attrs['href']
link

properties = soup.find_all('div', class_ = 'col-list-items')

for prop in properties:
    code  = prop.find('div', class_ = 'entry-code').text
    desc  = prop.find('p', class_ = 'entry-desc').text
    area  = prop.find('p', class_ = 'entry-area').text
    price = prop.find('p', class_ = 'entry-price').text
    image = prop.find('img').attrs['src']
    link  = prop.find('a').attrs['href']
    print(f'Code : {code}')
    print(f'Desc : {desc}')
    print(f'Area : {area}')
    print(f'Price: {price}')
    print(f'Image: {image}')
    print(f'Link : {link}')
    print()

### Find links to pagination (next/previous pages)

pagination = soup.find('ul', class_ = 'pagination')
pagination.prettify()

line = pagination.find('li', class_ = 'active')
line

hlink = pagination.find('a', class_ = 'next').attrs['href']
hlink

### Browse to the next page

nextpage = requests.get(hlink)
soup = BeautifulSoup(nextpage.text, 'html')
soup

### Then extract information as before

properties = soup.find_all('div', class_ = 'col-list-items')

for prop in properties:
    code  = prop.find('div', class_ = 'entry-code').text
    desc  = prop.find('p', class_ = 'entry-desc').text
    area  = prop.find('p', class_ = 'entry-area').text
    price = prop.find('p', class_ = 'entry-price').text
    image = prop.find('img').attrs['src']
    link  = prop.find('a').attrs['href']
    print(f'Code : {code}')
    print(f'Desc : {desc}')
    print(f'Area : {area}')
    print(f'Price: {price}')
    print(f'Image: {image}')
    print(f'Link : {link}')
    print()

Code : P00186
Desc : ห้องชุดเลขที่ 950/52 ชั้น 6 โครงการบ้านอุดมสุขคอนโดมิเนี่ยม 2 ซอยอุดมสุข 42 (บางนาตราด 19 แยก 14) ถนนอุดมสุข แขวงบางนา เขตพระโขนง กรุงเทพมหานคร
Area : 0000-0-00.0 / 23.37 ตร.ม.
Price: 234,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3746_20220512114823.jpg
Link : https://www.ttbbank.com/property/property/detail/P00186

Code : C10125
Desc : ห้องชุดเลขที่ 1638/90 โครงการ 101 แมนชั่นคอนโดมิเนียม ถนนลาดพร้าว ซอย 101 แยก 38 (สันติสุข) แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร
Area : 0000-0-00.0 / 33.56 ตร.ม.
Price: 425,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3013_20210621171407.jpg
Link : https://www.ttbbank.com/property/property/detail/C10125

Code : B12100
Desc : 477/18 ชั้น 2 อาคาร ซี อาคารชุดเทพลีลา คอนโดทาวน์ ซอยพระยาประเสริฐ แขวงวังทองหลาง เขตบางกะปิ กรุงเทพมหานคร
Area : 0000-0-00.0 / 24.3 ตร.ม.
Price: 454,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3919_20220803201316.jpg
Link : https://www.ttbbank.com/property/property/detail/B12100

Code : P00001
Desc : 312/213 ชั้น 7 อาคาร A อาคารชุดบ้านพระยาภิรมย์-รัชดา ซอยรัชดาภิเษก 36 (เสือใหญ่อุทิศ) แยก 11  แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร
Area : 0000-0-00.0 / 31.86 ตร.ม.
Price: 513,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3789_20220511143250.jpg
Link : https://www.ttbbank.com/property/property/detail/P00001

Code : P00212
Desc : 3272/110 ชั้น 5 อาคาร อี2 อาคารชุดซิตี้ วิลล่า ซอยลาดพร้าว126 ถนนลาดพร้าว แขวงคลองจั่น เขตบางกะปิ กรุงเทพมหานคร
Area : 0000-0-00.0 / 32.88 ตร.ม.
Price: 902,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/2602_20210216142619.jpg
Link : https://www.ttbbank.com/property/property/detail/P00212

Code : B12648
Desc : 16/129 ชั้น 5 อาคาร E อาคารชุดสมาร์ทคอนโด พระราม 2 ถนนบางขุนเทียน 16 แขวงแสมดำ เขตบางขุนเทียน กรุงเทพมหานคร
Area : 0000-0-00.0 / 28.5 ตร.ม.
Price: 1,004,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/2489_20201103165949.jpg
Link : https://www.ttbbank.com/property/property/detail/B12648

Code : B12776
Desc : 99/83 ชั้นล่าง อาคารบี อาคารชุดลุมพินี คอนโดทาวน์ บางแค  ถนนบางแค แขวงบางแค เขตบางแค กรุงเทพมหานคร
Area : 0000-0-00.0 / 26.31 ตร.ม.
Price: 1,188,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3825_20220605081231.jpg
Link : https://www.ttbbank.com/property/property/detail/B12776

Code : C10114
Desc : ห้องชุดเลขที่ 104/78 ชั้น4 อาคาร 3 โครงการไอริส แอเวนิว ถนนลาดกระบัง แขวงลาดกระบัง เขตลาดกระบัง กรุงเทพมหานคร
Area : 0000-0-00.0 / 28.01 ตร.ม.
Price: 1,263,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3067_20210617172431.jpg
Link : https://www.ttbbank.com/property/property/detail/C10114

Code : P00323
Desc : ห้องชุดเลขที่ 1/30 อาคาร เอ ชั้น 2 โครงการลุมพินีวิลล์ อ่อนนุช-พัฒนาการ ซอยอ่อนนุช 55-1 ถนนอ่อนนุช แขวงประเวศ เขตประเวศ กรุงเทพมหานคร
Area : 0000-0-00.0 / 22.66 ตร.ม.
Price: 1,322,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3690_20220406191527.jpg
Link : https://www.ttbbank.com/property/property/detail/P00323

Code : B12196
Desc : 45 ซอยเพชรเกษม 79 แยก 1 ถนนเพชรเกษม แขวงหนองค้างพลู เขตหนองแขม กรุงเทพมหานคร
Area : 0000-0-20.0 / 20 ตร.ว.
Price: 1,400,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/281_20200220095812.jpg
Link : https://www.ttbbank.com/property/property/detail/B12196

Code : P00365
Desc : ห้องชุดเลขที่ 194/101 ชั้น 4 อาคาร D โครงการเมโทรพาร์ค สาทร 3-2 ถนนกัลปพฤกษ์ แขวงบางหว้า เขตภาษีเจริญ กรุงเทพมหานคร
Area : 0000-0-00.0 / 31.61 ตร.ม.
Price: 1,496,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3117_20210621172149.jpg
Link : https://www.ttbbank.com/property/property/detail/P00365

Code : P00361
Desc : ห้องชุดเลขที่  164/74 ชั้น 7 อาคาร E โครงการเมโทรพาร์ค สาทร 2-2 แขวงบางหว้า เขตภาษีเจริญ กรุงเทพมหานคร
Area : 0000-0-00.0 / 30.1 ตร.ม.
Price: 1,524,000บาท
Image: https://media.tmbbank.com/uploads/npa/product/img/3113_20210617120555.jpg
Link : https://www.ttbbank.com/property/property/detail/P00361